---
title: "mid_std"
author: "周聖諺"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gaussian Mixture

```{r}
update_log_Lambda_k <- function(k, nu_k, D, W_k){
  return(sum(digamma((nu_k[k] + 1 - 1:D)/2)) + D*log(2) + log(det(W_k[,,k])))
}

update_m_k <- function(k, beta_k, m_0, N_k, x_bar_k){
  return((1/beta_k[k]) * (beta_0*m_0 + N_k[k]*x_bar_k[, k]))
}

update_log_pi <- function(alpha){
  return(digamma(alpha) - digamma(sum(alpha)))
}

update_pi_k <- function(alpha_0, N_k, K, N){
  return((alpha_0 + N_k) / (K * alpha_0 + N))
}
```

## Gaussian-Wishart

```{r}
update_W_k <- function(k, W_0_inv, N_k, S_k, beta_0, x_bar_k, m_0){
  W_k <- W_0_inv + 
         N_k[k] * S_k[,,k] + 
         ((beta_0*N_k[k])/(beta_0 + N_k[k])) * tcrossprod((x_bar_k[, k] - m_0))
  return(solve(W_k))
}

update_nu_k <- function(nu_0, N_k){
  return(nu_0 + N_k + 1)
}

update_beta_k <- function(beta_0, N_k){
  return(beta_0 + N_k)
}
```

## Dirichlet

```{r}
update_alpha <- function(alpha_0, N_k){
  return(alpha_0 + N_k) # 10.58
}
```


## Variational Bayesian Gaussian Mixture Model

```{r}
VB_GMM <- function(X, 
                   K=3,
                   m_0=c(colMeans(X)),
                   beta_0=1,
                   nu_0=NCOL(X)+50,
                   W_0=diag(100, NCOL(X)),
                   max_iter=1000,
                   threshold=1e-4,
                   epsilon=1e-10,
                   is_animation=FALSE,
                   is_verbose=FALSE){
  
  # Some Essential Variables
  X <- as.matrix(X)
  # Number of features
  D <- NCOL(X)
  # Number of data points
  N <- NROW(X)
  
  # Gaussian Mixture
  GM <- structure(list(log_pi=rep(0, K), pi_k=0), class="Gaussian-Mixture")
  
  # Gaussian Wishart
  GW <- structure(list(W_0=W_0,
                       W_0_inv=solve(W_0), 
                       W_k=array(0, c(D, D, K)), 
                       log_Lambda=rep(0, K),
                       m_0=m_0,
                       m_k=t(kmeans(X, K, nstart = 25)$centers), # Scale of precision matrix
                       beta_0=beta_0,
                       beta_k=rep(beta_0, K), # Degrees of freedom
                       nu_0=nu_0,
                       nu_k=rep(nu_0, K)), # Degrees of freedom
                   class="Gaussian-Wishart")
  
  # Dirichlet 
  DIR <- structure(list(alpha_0=alpha_0, 
                        alpha=rep(alpha_0, K)), 
                   class="Dirichlet")
  
  # ELBO
  L <- rep(-Inf, max_iter)  # Store the lower bounds
  
  # Utility Variable
  UTIL <- structure(list(r_nk=matrix(0, nrow=N, ncol=K), 
                         log_r_nk=matrix(0, nrow=N, ncol=K), 
                         log_rho_nk=matrix(0, nrow=N, ncol=K), 
                         x_bar_k=matrix(0, nrow=D, ncol=K),
                         S_k=array(0, c(D, D, K)),
                         N_k=0), 
                    class="Utility")
}
```